apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway-hashicup
  namespace: consul
spec:
  listeners:
    - port: 8888
      protocol: http
      services:
        - name: nginx
          hosts: ["*"]
