apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api-hashicup
spec:
  sources:
    - name: nginx
      action: allow
  destination:
    name: public-api
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: products-api-hashicup
spec:
  sources:
    - name: public-api
      action: allow
  destination:
    name: products-api
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  sources:
    - name: public-api-hashicup
      action: allow
  destination:
    name: payments
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: postgres
spec:
  sources:
    - name: products-api-hashicup
      action: allow
  destination:
    name: postgres
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend-hashicup
spec:
  sources:
    - name: nginx
      action: allow
  destination:
    name: frontend
